### ISSUE TITLE
Win7: Can't select a portion of remote URL

### ISSUE THREAD

**Issue by jheigl** [amweiss/vigilant-cupcake#1]
When trying to select a portion of a remote URL entry to change, double clicking selects the entire URL. For example, in the tool, if https://github.com/amweiss/vigilant-cupcake was my remote host URL, if I wanted to select and change amweiss to jheigl by double clicking amweiss, it selects the entire URL entry. I would have to manually highlight the section I want to change.

**Comment by amweiss** [comment]
This appears to be part of the default behavior of the component and is non-trivial to override.

I'll move this to enhancement and try to get to it later.

**Comment by amweiss** [comment]
Fixed in 7a71a459305e301a1fe92a72a5f88fe27bbf2783
