### ISSUE TITLE
Win7: Can't right-click unhighlighted fragment in the list

### ISSUE THREAD

**Issue by jheigl** [amweiss/vigilant-cupcake#2]
When working in the Fragment List window (left-most window), the user cannot right-click on a fragment in the list that is not highlighted already. For example, if I have two fragments in the list, named FragmentOne and FragmentTwo, I left-click on FragmentOne, I can right-click on it. I cannot right-click on FragmentTwo while FragmentOne is highlighted.

**Comment by amweiss** [comment]
This is currently by design, would you expect to be able to right click and edit something that's not selected or should the selection change to the item you right clicked?

**Comment by jheigl** [comment]
Either or would be fine, but my preference would be to be able to right click and edit a name or something on a fragment whether it is selected or not.

**Comment by amweiss** [comment]
Added in 0b311de624e560f1ca50d290bfcf5d755250647e.  Right click now selects and shows context menu.
