### ISSUE TITLE
[Request] Manually sync fragments

### ISSUE THREAD

**Issue by jheigl** [amweiss/vigilant-cupcake#22]
Would be fantastic to have the ability to manually sync a remote fragment on demand. Perhaps when right clicking on a fragment, the option can be put in that menu?

**Comment by amweiss** [comment]
Added in 58cd3d1e3e34776054dc29f2914facef2cff5b8e, I won't be pushing a release for this, but you can download it [here](https://cdn.rawgit.com/amweiss/vigilant-cupcake/58cd3d1e3e34776054dc29f2914facef2cff5b8e/VigilantCupcake/bin/Release/vigilantcupcake.zip)
