### ISSUE TITLE
Provide option to ignore SSL errors

### ISSUE THREAD

**Issue by amweiss** [amweiss/vigilant-cupcake#31]
For fun with things like self-signed certs, add the option to ignore SSL errors.

**Comment by AKermodeBear** [comment]
I will cook a salmon in your honor if you implement this.

**Comment by amweiss** [comment]
I'm holding this hostage until my Sam karma is 0 or higher.

**Comment by jheigl** [comment]
...that'll be a while...

**Comment by AKermodeBear** [comment]
You're backup on call this week. I'm primary. Don't make me not answer my
phone.

(o:<

**Comment by amweiss** [comment]
This should be on the master branch with commit 159f5d37a012c9856a8d01c584fbb7724365a293, however, I can't test it.  So you need someone to give me a publicly accessible URL with a self-signed cert or download and compile it yourself.

**Comment by amweiss** [comment]
Should be in the latest release.  Might take a few restarts to get updated to 1.1.16.

**Comment by AKermodeBear** [comment]
2:18 PM Dr. Rev. Bear: sam, aweiss++
2:18 PM sam: [karma] drrevbear: aweiss now has -306 karma.
