### ISSUE TITLE
Unable to start the Cupcake

### ISSUE THREAD

**Issue by ragingdave** [amweiss/vigilant-cupcake#33]
Upon initial running, I get an error message saying:
Could not find file: 'F:\Documents\VigilantCupcake\New Fragment.txt'.

This is a fresh installation, Win8.1.

**Comment by amweiss** [comment]
Hm, fresh install just worked for me on 8.1, but I have my documents on C.

Where is your %localappdata% directory?  I wonder if I missed a relative vs. absolute reference somewhere.

**Comment by ragingdave** [comment]
My %localappdata% points to C:\Users\USER\AppData\Local which seems normal....the only difference is that that my Downloads (where the Setup.exe is) is on F:\Downloads...Maybe that is something?

**Comment by amweiss** [comment]
Well the program runs out of localappdata, but stores the fragments in documents. I'll see what I can find.

**Comment by amweiss** [comment]
Hopefully fixed with 0c2009d59045f6ff1c32ecbea49c73883992d72c give it a try.
