### ISSUE TITLE
Win7: Copying a URL in the right-most window will copy some program code into Pidgin window

### ISSUE THREAD

**Issue by jheigl** [amweiss/vigilant-cupcake#4]
When copying a URL in the right-most window, then pasting that URL in a Pidgin chat window, it pastes (for example):

.fctbNone{ color:#000000; } anyurlhere.com

When pasting the copied link in a browser, text editor, etc, I did not see this occur.

**Comment by amweiss** [comment]
This appears to be due to the control filling the HTML and plain text parts of the clipboard and pidgin not handling it correctly, I'll see what I can do.

**Comment by amweiss** [comment]
Looks like this is a pidgin bug, if you right click and do "paste as plain text" it should do what you expect.
