### ISSUE TITLE
Win7: Save on Program Start overwrites current (remote) hosts file and saves Loading...

### ISSUE THREAD

**Issue by jheigl** [amweiss/vigilant-cupcake#5]
When a remote hosts file (or multiple) are the current hosts file, closing the program and reopening it when Save at Program Start is selected, your hosts file will be overwritten to show the Loading... entries in your hosts file.

![save on startup](https://cloud.githubusercontent.com/assets/10598892/5802135/0d6423ca-9fc0-11e4-840c-16478e66dbc5.png)

**Comment by amweiss** [comment]
Fixed in 1e3eec8c16e380e682909e87c81e06b03783f92e
