### ISSUE TITLE
Win7: Non-txt file fragments appear in the list

### ISSUE THREAD

**Issue by jheigl** [amweiss/vigilant-cupcake#6]
In the screenshot below, the Fragments list shows non-txt files. The .rar file is filled with txt files, but this entry should not be shown in the Fragments list.

![fragments](https://cloud.githubusercontent.com/assets/10598892/5802172/6fc42074-9fc0-11e4-9294-e7b6887c9fdd.png)

**Comment by amweiss** [comment]
Ah, it currently lists everything as it doesn't define a file extension.  I'll include this with #7.
