### ISSUE TITLE
Suggestion: Win7: Save hosts as .txt

### ISSUE THREAD

**Issue by jheigl** [amweiss/vigilant-cupcake#7]
This is just a suggestion, but perhaps it might be a worthwhile idea to save the hosts as a txt file or some other filetype that is easily opened by a text editor. Currently it shows as just a 'File' type. While this can easily still be opened with a text editor, some users may not be aware of this. 

![hosts](https://cloud.githubusercontent.com/assets/10598892/5802229/f6dc7854-9fc0-11e4-8841-50daa93bbb50.png)

Along the same lines, if a user copies over an existing saved hosts file with an extension in the filename, such as myhosts.txt, the Fragments list will show the .txt extension in the list. Not that this is terrible, but might look cleaner to strip the extension in the Fragments list.

**Comment by amweiss** [comment]
Ensure that the fragment list only shows .txt files if this feature is added.

**Comment by amweiss** [comment]
Added in b0765ec3efbe231d1ed90c7321256772dae325e6
